In [1]:
import numpy as np
import math

In [2]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
delta_time1 = 100e-9
delta_time2 = 30e-6
coherence_time = 300e-6

In [4]:
#t = delta_time1
#tau = coherence_time
#np.exp(-t/tau)

In [5]:
"""
def IonPhotonDephaseNoiseModel(delta_time, coherence_time):
    temp = np.exp(-delta_time/coherence_time)
    
    if coherence_time != 0:
        rotation_matrix = 
    else:
        rotation_matrix = I
        rotation_operator = Operator(name='rotation_oeprator', matrix=rotation_matrix, 
                                     description='collective dpehasing operator, rotation rate has been sampled')
"""


"\ndef IonPhotonDephaseNoiseModel(delta_time, coherence_time):\n    temp = np.exp(-delta_time/coherence_time)\n    \n    if coherence_time != 0:\n        rotation_matrix = \n    else:\n        rotation_matrix = I\n        rotation_operator = Operator(name='rotation_oeprator', matrix=rotation_matrix, \n                                     description='collective dpehasing operator, rotation rate has been sampled')\n"

In [6]:
A = np.matrix([[0, 1], [1, 0]])

In [7]:
B = np.matrix([[2, 3], [4, 5]])

In [8]:
C = np.tensordot(A, B, axes=0)
print(C)

[[[[0 0]
   [0 0]]

  [[2 3]
   [4 5]]]


 [[[2 3]
   [4 5]]

  [[0 0]
   [0 0]]]]


In [9]:
D = C.flatten()
D

array([0, 0, 0, 0, 2, 3, 4, 5, 2, 3, 4, 5, 0, 0, 0, 0])

In [10]:
E = np.array([])

In [11]:
for i in D:
    if i > 0:
        E = np.append(E, i)

In [12]:
print(E)

[2. 3. 4. 5. 2. 3. 4. 5.]


In [13]:
input_density_matrix = np.matrix([[0, 1], [1, 0]])
rotation_matrix = input_density_matrix.copy()
delta_time = 60e-6
coherence_time = 300e-6
intm = np.exp(-delta_time / coherence_time)

[[[0 0]
  [0 0]]

 [[2 3]
  [4 5]]]
[[0 0]
 [0 0]]
[[2 3]
 [4 5]]
[[[2 3]
  [4 5]]

 [[0 0]
  [0 0]]]
[[2 3]
 [4 5]]
[[0 0]
 [0 0]]


In [ ]:
aa

In [ ]:
for x in C:
    for y in x:
        for i in y:
            E = np.append(i)
            